version: '3'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefic.yaml:/etc/traefik/traefik.yaml 
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8090
    ports:
      - "8090:8090"
    
  user:
    container_name: user-service
    build: ./user-service
    ports:
      - "8081:8081"

    # user:
  #   container_name: user-service
  #   build: /home/mikhail/restaurant/user-service
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - postgres
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    

  # postgres:
  #   container_name: postgres
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: